services:
  db:
    image: mariadb:10.6
    container_name: db
    restart: always
    volumes:
      - db:/var/lib/mysql
    env_file: ./mariadb/.env
    networks:
      skycloud-network:
        ipv4_address: 10.10.10.2

  redis:
    image: redis:alpine
    restart: always
    networks:
      skycloud-network:
        ipv4_address: 10.10.10.30

  onlyoffice-document-server:
    container_name: onlyoffice-document-server
    image: onlyoffice/documentserver:latest
    restart: always
    env_file: ./nextcloud/only-office/.env
    expose:
      - '80'
      - '443'
    volumes:
      - document_data:/var/www/onlyoffice/Data
      - document_log:/var/log/onlyoffice
    networks:
      skycloud-network:
        ipv4_address: 10.10.10.8

  nextcloud-fpm:
    image: nextcloud:fpm-alpine
    container_name: nextcloud-fpm
    restart: always
    expose:
      - 80
      - 9000
    volumes:
      - nextcloud:/var/www/html:z
    environment:
      - MYSQL_HOST=db
      - REDIS_HOST=redis
    env_file:
      - ./nextcloud/.env
    depends_on:
      - db
      - redis
    networks:
      skycloud-network:
        ipv4_address: 10.10.10.5

  nextcloud-web:
    build: ./nextcloud/web
    container_name: nextcloud-web
    restart: always
    volumes:
      - nextcloud:/var/www/html:z,ro
    environment:
      - VIRTUAL_HOST=nextcloud.skylab.com
      - LETSENCRYPT_HOST=
      - LETSENCRYPT_EMAIL=
    depends_on:
      - nextcloud-fpm
    networks:
      skycloud-network:
        ipv4_address: 10.10.10.6

  nextcloud-cron:
    image: nextcloud:fpm-alpine
    container_name: nextcloud-cron
    restart: always
    volumes:
      - nextcloud:/var/www/html:z
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis
    networks:
      skycloud-network:
        ipv4_address: 10.10.10.7
 
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs/mycert.key:/etc/nginx/mycert.key
      - ./certs/mycert.crt:/etc/nginx/mycert.crt
      - ./nginx/conf.d/.:/etc/nginx/conf.d/.
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"

    networks:
      skycloud-network:
        ipv4_address: 10.10.10.3

  stirling_pdf:
    image: frooodle/s-pdf:latest
    container_name: stirling_pdf
    volumes:
      - trainingData:/usr/share/tessdata 
      - extraConfigs:/configs
#      - ./customFiles:/customFiles/
#      - ./logs:/logs/
    environment:
      - DOCKER_ENABLE_SECURITY=false
      - INSTALL_BOOK_AND_ADVANCED_HTML_OPS=false
      - LANGS=en_GB
    networks:
      skycloud-network:
        ipv4_address: 10.10.10.20

networks:
  skycloud-network:
    name: skycloud-network
    ipam:
      config:
        - subnet: 10.10.10.0/24
volumes:
  nextcloud:
    name: "nextcloud"
  db:
    name: "db"
  trainingData: 
    name: "stirling-pdf-trainingData"
  extraConfigs:
    name: "stirling-pdf-extraConfig"
  document_data:
    name: "onlyoffice-document-data"
  document_log:
    name: "onlyoffice-document-log"

