services:
  nextcloud-db:
    image: mariadb:10.6
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    env_file:
      - mariadb/.env
    networks:
      - nextcloud

  nextcloud-app:
    image: nextcloud
    restart: always
    ports:
      - 8080:80
    links:
      - nextcloud-db
    volumes:
      - nextcloud:/var/www/html
    env_file:
      - nextcloud/.env
    networks:
      - shared
      - nextcloud

  collabora:
    image: collabora/code:24.04.13.1.1
    container_name: "collabora"
    ports:
      - 9980:9980/tcp
    restart: always
    env_file:
      - collabora/.env
    cap_add:
      - MKNOD
    networks:
      - nextcloud

networks:
  shared:
    external: true
  nextcloud:

volumes:
  nextcloud:
  db:
