services:
  db:
    image: mariadb:10.6
    container_name: db
    restart: always
    volumes:
      - db:/var/lib/mysql
      - "/etc/localtime:/etc/localtime:ro"
    env_file: ./mariadb/.env
    networks:
      skycloud-network:
    expose:
      - 3306

  redis:
    image: redis:alpine
    restart: always
    networks:
      - skycloud-network
    expose:
      - 6379
    volumes:
      - "/etc/localtime:/etc/localtime:ro"

  nc:
    image: nextcloud
    restart: always
    expose:
      - 80
      - 9000
    environment:
      - MYSQL_HOST=db
      - REDIS_HOST=redis
    env_file:
      - ./nextcloud/.env
    # ports:
    #   - 80:80
    volumes:
      - nextcloud:/var/www/html
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      - skycloud-network

  collabora:
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
    expose:
      - 9980
    ports:
      - 9980:9980
    environment:
      - domain=cloud\.yildizskylab\.com
      - server_name=loolwsd.yildizskylab.com
      - "extra_params=--o:ssl.enable=false --o:ssl.termination=true"
    restart: always
    cap_add:
      - MKNOD
    image: collabora/code
    networks:
      - skycloud-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./certs/mycert.key:/etc/nginx/mycert.key
      - ./certs/mycert.crt:/etc/nginx/mycert.crt
      - ./nginx/conf.d/.:/etc/nginx/conf.d/.
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      - "extra_params=--o:ssl.enable=false  --o:ssl.termination=false"
    networks:
      skycloud-network:


networks:
  skycloud-network:
    name: skycloud-network
    ipam:
      config:
        - subnet: 10.10.10.0/24

volumes:
  nextcloud:
    name: "nextcloud"
  db:
  document_data:
  document_log:
    name: "onlyoffice-document-log"

