services:
  db:
    image: mariadb:10.6
    container_name: db
    restart: always
    volumes:
      - db:/var/lib/mysql
      - "/etc/localtime:/etc/localtime:ro"
    env_file: ./mariadb/.env
    networks:
      skycloud-network:
    expose:
      - 3306

  redis:
    image: redis:alpine
    restart: always
    networks:
      - skycloud-network
    expose:
      - 6379
    volumes:
      - "/etc/localtime:/etc/localtime:ro"

  nc:
    image: nextcloud
    restart: always
    env_file:
      - ./nextcloud/.env
    ports:
      - 80:80
    volumes:
      - nextcloud:/var/www/html/data
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      - skycloud-network

  collabora:
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
    expose:
      - 9980
    ports:
      - 9980:9980
    environment:
      - domain=cloud\.yildizskylab\.com
      - server_name=loolwsd.yildizskylab.com
      - "extra_params=--o:ssl.enable=false --o:ssl.termination=true"
    restart: always
    cap_add:
      - MKNOD
    image: collabora/code
    networks:
      - skycloud-network



networks:
  skycloud-network:
    name: skycloud-network
    ipam:
      config:
        - subnet: 10.10.10.0/24

volumes:
  nextcloud:
  db:

