services:
 nginx:
  image: nginx:alpine
  container_name: nginx-site-to-site
  restart: always
  ports:
    - 80:80
    - 443:443
  volumes:
    # Self Signed
     - ./mycert.key:/etc/nginx/mycert.key
     - ./mycert.crt:/etc/nginx/mycert.crt
     - ./conf.d/.:/etc/nginx/conf.d/.
     - ./variables.conf:/etc/nginx/templates/variables.conf.template:ro
  labels:
    com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
  environment:
    EXTERNAL_IP: "10.8.0.2"
